### ISSUE TITLE
Migrate to PagerDuty API v2

### ISSUE THREAD

**Issue by pedrofuentes** [PedroFuentes/my-bitbar-plugins#1]

**Comment by manos** [comment]
Hi! I notice this is closed, but the code still references the v1 API. I think they are about to turn off v1.. any plans to do the migration by chance? :)

**Comment by pedrofuentes** [comment]
Hi @manos #708 is closed but this enhancement is still open, I do not have plans yet to work on this if you want to contribute you are welcome.

**Comment by ksonney** [comment]
V1 API is no longer available, FYI. Neither of these plugins work now.

**Comment by pedrofuentes** [comment]
@manos and @ksonney I just upgraded the plugins to use v2, enjoy.
